openapi: '3.1.0'
info:
  title: GreetingService
  version: 1.0.0
servers:
  - url: http://127.0.0.1/openapi
    description: Example service deployment.
paths:
  /image:
    get:
      operationId: getImage
      responses:
        '200':
          description: A Cat image.
          content:
            image/jpeg:
              schema:
                type: string
                format: binary
  /json:
    get:
      operationId: getJSON
      responses:
        '200':
          description: A JSON.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloVapor'
components:
  schemas:
    HelloVapor:
      type: object
      properties:
        message:
          type: string
        status:
          type: string
      required:
        - message
        - status
